site_name: FaBo Physical Agent Kit Docs
site_url: https://pak.fabo.io/
theme:
    name: material
    custom_dir: 'theme'
    language: 'ja'
    palette:
      primary: 'yellow'
      accent: 'black'
    logo: 'logo.png'
    favicon: 'favicon.png'
extra:
    search:
        language: 'jp'
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      noclasses: false
      pygments_style: monokai
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - admonition
  - pymdownx.keys
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: "index.md"
  - LeRobot:
    - 接続の確認: "lerobot/check.md"
    - 各種値の設定: "lerobot/common.md"
    - キャリブレーション: "lerobot/calibration.md"
    - カメラの調整: "lerobot/camera.md"
    - データセットの収集: "lerobot/collect.md"
    - データセットの編集: "lerobot/edit.md"
    - 学習: "lerobot/train.md"
    - 推論の実行: "lerobot/run.md"
    - ノウハウ: "lerobot/knowhow.md"
    - データセット: "lerobot/dataset.md"
  - LeRobotプラグイン:
    - Teleopプラグイン: "core/teleop.md"
    - Robotプラグイン: "core/robot.md"
    - Toio Leaderプラグイン: "core/toio_teleop.md"
    - Toio Followerプラグイン: "core/toio_robot.md"
    - Toio Command: "core/toio_command.md"
  - FaBo Physical Agent Kit:
    - 配置と配線: "jetson/build.md"
    - 動作確認: "jetson/first.md"
  - 各種設定:
    - Firmware: "setting/firmware.md"
    - ID割り振り: "setting/id.md"
    - 環境構築: "jetson_orin/setting.md"
    - 各種設定: "jetson_orin/setup.md"
  - その他:
    - GR00T:
      - 環境構築: "gr00t/env.md"
    - SmolVLA:
      - 環境構築: "smolvla/setting.md"
    - HilSerl:
      - 環境構築: "hilsel/setting.md"
    - Rerun.io:
      - Trouble Shooting: "rerun/trouble.md"
    - Jetson AGX Orin:
      - GMSL Camera: "jetson_agx/gmsl_camera.md"
      
extra_css:
#  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
#  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
#  - "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css"
  - "css/version-select.css"
  - "css/custom.css"
  - "stylesheets/lerobot_ports.css"
  - "css/heading-icons.css"
extra_javascript:
  - javascripts/version-select.js
  - javascripts/extra.js
  - javascripts/lerobot_ports.js
  - "javascripts/heading-icons.js"
plugins:
  - macros
  - mkdocs-video